-- Realign the Payment.receiptNumber identity sequence with the rows that
-- actually exist.
--
-- Recording a deposit failed for EVERY role -- reception, admin, anyone holding
-- `payment.record` -- with:
--
--   PrismaClientKnownRequestError: Invalid `prisma.payment.create()` invocation:
--   Unique constraint failed on the fields: (`receiptNumber`)
--
-- Cause: `Payment.receiptNumber` is `GENERATED BY DEFAULT AS IDENTITY`, so an
-- INSERT that omits the column takes `nextval` from the sequence. But 25 rows
-- exist with receiptNumber 5001..5025 while the sequence still stood at 5003 --
-- it had never been advanced past them. The next `nextval` returned 5004, which
-- already existed, and the UNIQUE constraint rejected the row. Every subsequent
-- deposit would have collided too: the sequence was 22 values behind and moving
-- away, not catching up.
--
-- This is the classic "identity sequence out of sync with the table" state. It
-- happens whenever rows land in an identity column with an explicit value rather
-- than through the sequence -- a hand-run INSERT, a data import, a restore from
-- a dump. This database is shared with the test harness (DATABASE_URL_TEST and
-- DATABASE_URL resolve to the same physical database), which widens the window
-- for exactly that kind of ad-hoc write.
--
-- It is worth being explicit about why this was invisible until now: the app
-- never touched `Payment` on the reception save path before the deposit field
-- was added, so a broken receipt sequence could not surface. The moment
-- `recordPayment` became reachable, every deposit hit it.
--
-- `setval` is the repair, and `pg_get_serial_sequence` is used rather than a
-- hard-coded sequence name so the migration follows the column rather than
-- assuming the name Postgres happened to generate.
--
-- The third argument to `setval` is `is_called`, and it is the difference
-- between correct and off-by-one for an EMPTY table. With `true`, `nextval`
-- returns value + 1; with `false` it returns the value itself. A shop that has
-- recorded no payments at all must therefore get `false`, or its first receipt
-- number would be 2.
--
-- Idempotent by construction: the value is always derived from MAX(), so
-- re-running this converges to the same answer and can never lower the sequence
-- below a value already in use.
--
-- Order.number is resynced in the same statement block. It is NOT currently
-- drifted, and this leaves it exactly where it is -- but it is the same kind of
-- identity column, it gets the same treatment from any hand-run INSERT, and the
-- cost of checking it here is one line next to the repair for the column that
-- is actually broken.
DO $$
DECLARE
  payment_max bigint;
  order_max   bigint;
BEGIN
  SELECT COALESCE(MAX("receiptNumber"), 0) INTO payment_max FROM "Payment";
  PERFORM setval(
    pg_get_serial_sequence('"Payment"', 'receiptNumber'),
    GREATEST(payment_max, 1),
    payment_max > 0
  );

  SELECT COALESCE(MAX(number), 0) INTO order_max FROM "Order";
  PERFORM setval(
    pg_get_serial_sequence('"Order"', 'number'),
    GREATEST(order_max, 1),
    order_max > 0
  );
END
$$;