-- 052-finance — additive migration (T005).
--
-- Contents (specs/052-finance/data-model.md):
--   1. FinanceVoidEntity enum.
--   2. Payment, FinanceVoid, Expense, ExpenseApproval, DirectCost,
--      CustomerCredit, FinanceConfig tables + indexes + FKs.
--   3. CHECK constraints: positive money amounts, non-empty void reason,
--      non-negative credit limit (Prisma-expressible checks live in schema
--      where possible; these DB checks are defense in depth alongside the
--      application-layer Zod validation — FR-026).
--   4. Append-only enforcement triggers: Payment / Expense / DirectCost /
--      FinanceVoid / ExpenseApproval rows are never updated or deleted —
--      corrections are appended FinanceVoid rows, approval an appended
--      ExpenseApproval row (constitution III, FR-004/FR-016, 051 pricing
--      precedent). scripts/test-db.mjs additionally REVOKEs UPDATE/DELETE
--      from the test app role so tests prove the refusal directly (SC-002).
--   5. Backfill: one FinanceConfig singleton seeded from
--      config/052-finance.yaml defaults (methods/sources/categories/
--      threshold/timezone) so configuration exists before first use.
--
-- Replay-safe: IF NOT EXISTS / guarded DO blocks; re-run is a no-op.

-- --- 1. Enums ---------------------------------------------------------------

DO $$ BEGIN
  CREATE TYPE "FinanceVoidEntity" AS ENUM ('PAYMENT', 'EXPENSE', 'DIRECT_COST');
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

-- --- 2. Tables --------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Payment" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'EGP',
    "method" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "note" TEXT,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "recordedById" TEXT NOT NULL,
    "receiptNumber" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Payment_receiptNumber_key" UNIQUE ("receiptNumber")
);

CREATE TABLE IF NOT EXISTS "FinanceVoid" (
    "id" TEXT NOT NULL,
    "entityType" "FinanceVoidEntity" NOT NULL,
    "entityId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "voidedById" TEXT NOT NULL,
    "voidedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FinanceVoid_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "FinanceVoid_entityType_entityId_key" UNIQUE ("entityType", "entityId")
);

CREATE TABLE IF NOT EXISTS "Expense" (
    "id" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "category" TEXT NOT NULL,
    "expenseDate" TIMESTAMP(3) NOT NULL,
    "employee" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "orderId" TEXT,
    "workItemId" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ExpenseApproval" (
    "expenseId" TEXT NOT NULL,
    "approvedById" TEXT NOT NULL,
    "approvedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ExpenseApproval_pkey" PRIMARY KEY ("expenseId")
);

CREATE TABLE IF NOT EXISTS "DirectCost" (
    "id" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "costDate" TIMESTAMP(3) NOT NULL,
    "description" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "workItemId" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DirectCost_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "CustomerCredit" (
    "customerId" TEXT NOT NULL,
    "creditApproved" BOOLEAN NOT NULL DEFAULT false,
    "creditLimit" DECIMAL(12,2),
    "updatedById" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "CustomerCredit_pkey" PRIMARY KEY ("customerId")
);

CREATE TABLE IF NOT EXISTS "FinanceConfig" (
    "id" TEXT NOT NULL,
    "paymentMethods" JSONB NOT NULL,
    "paymentSources" JSONB NOT NULL,
    "expenseCategories" JSONB NOT NULL,
    "approvalThreshold" DECIMAL(12,2) NOT NULL,
    "shopTimezone" TEXT NOT NULL DEFAULT 'Africa/Cairo',
    "updatedById" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "FinanceConfig_pkey" PRIMARY KEY ("id")
);

-- --- 3. Indexes -------------------------------------------------------------

CREATE INDEX IF NOT EXISTS "Payment_orderId_idx" ON "Payment"("orderId");
CREATE INDEX IF NOT EXISTS "Payment_customerId_idx" ON "Payment"("customerId");
CREATE INDEX IF NOT EXISTS "Payment_occurredAt_idx" ON "Payment"("occurredAt");
CREATE INDEX IF NOT EXISTS "FinanceVoid_entityId_idx" ON "FinanceVoid"("entityId");
CREATE INDEX IF NOT EXISTS "Expense_orderId_idx" ON "Expense"("orderId");
CREATE INDEX IF NOT EXISTS "Expense_expenseDate_idx" ON "Expense"("expenseDate");
CREATE INDEX IF NOT EXISTS "Expense_category_idx" ON "Expense"("category");
CREATE INDEX IF NOT EXISTS "DirectCost_orderId_idx" ON "DirectCost"("orderId");
CREATE INDEX IF NOT EXISTS "DirectCost_workItemId_idx" ON "DirectCost"("workItemId");

-- --- 4. CHECK constraints (defense in depth beside Zod) ---------------------

DO $$ BEGIN
  ALTER TABLE "Payment" ADD CONSTRAINT "Payment_amount_positive" CHECK ("amount" > 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_amount_positive" CHECK ("amount" > 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "DirectCost" ADD CONSTRAINT "DirectCost_amount_positive" CHECK ("amount" > 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FinanceVoid" ADD CONSTRAINT "FinanceVoid_reason_nonempty" CHECK (length(btrim("reason")) > 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CustomerCredit" ADD CONSTRAINT "CustomerCredit_limit_positive" CHECK ("creditLimit" IS NULL OR "creditLimit" > 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- --- 5. Foreign keys --------------------------------------------------------

DO $$ BEGIN
  ALTER TABLE "Payment" ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Payment" ADD CONSTRAINT "Payment_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Payment" ADD CONSTRAINT "Payment_recordedById_fkey" FOREIGN KEY ("recordedById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FinanceVoid" ADD CONSTRAINT "FinanceVoid_voidedById_fkey" FOREIGN KEY ("voidedById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_workItemId_fkey" FOREIGN KEY ("workItemId") REFERENCES "WorkItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "ExpenseApproval" ADD CONSTRAINT "ExpenseApproval_expenseId_fkey" FOREIGN KEY ("expenseId") REFERENCES "Expense"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "ExpenseApproval" ADD CONSTRAINT "ExpenseApproval_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "DirectCost" ADD CONSTRAINT "DirectCost_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "DirectCost" ADD CONSTRAINT "DirectCost_workItemId_fkey" FOREIGN KEY ("workItemId") REFERENCES "WorkItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "DirectCost" ADD CONSTRAINT "DirectCost_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CustomerCredit" ADD CONSTRAINT "CustomerCredit_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CustomerCredit" ADD CONSTRAINT "CustomerCredit_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FinanceConfig" ADD CONSTRAINT "FinanceConfig_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;

-- --- 6. Append-only enforcement ---------------------------------------------
-- Money rows are never rewritten or deleted: a mistake is corrected by an
-- appended FinanceVoid row, an approval by an appended ExpenseApproval row
-- (spec FR-004, FR-005, FR-016; constitution III).

CREATE OR REPLACE FUNCTION finance_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION '% is append-only: rows are never deleted (052 constitution III)', TG_TABLE_NAME
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- UPDATE is refused wholesale on every finance table: no column of a
  -- Payment, Expense, DirectCost, FinanceVoid or ExpenseApproval row may
  -- change after insert (FR-004: no update path exists at all).
  RAISE EXCEPTION '% is append-only: rows are never updated (052 constitution III)', TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END $$;

DROP TRIGGER IF EXISTS "Payment_append_only" ON "Payment";
CREATE TRIGGER "Payment_append_only"
  BEFORE UPDATE OR DELETE ON "Payment"
  FOR EACH ROW EXECUTE FUNCTION finance_append_only();

DROP TRIGGER IF EXISTS "FinanceVoid_append_only" ON "FinanceVoid";
CREATE TRIGGER "FinanceVoid_append_only"
  BEFORE UPDATE OR DELETE ON "FinanceVoid"
  FOR EACH ROW EXECUTE FUNCTION finance_append_only();

DROP TRIGGER IF EXISTS "Expense_append_only" ON "Expense";
CREATE TRIGGER "Expense_append_only"
  BEFORE UPDATE OR DELETE ON "Expense"
  FOR EACH ROW EXECUTE FUNCTION finance_append_only();

DROP TRIGGER IF EXISTS "ExpenseApproval_append_only" ON "ExpenseApproval";
CREATE TRIGGER "ExpenseApproval_append_only"
  BEFORE UPDATE OR DELETE ON "ExpenseApproval"
  FOR EACH ROW EXECUTE FUNCTION finance_append_only();

DROP TRIGGER IF EXISTS "DirectCost_append_only" ON "DirectCost";
CREATE TRIGGER "DirectCost_append_only"
  BEFORE UPDATE OR DELETE ON "DirectCost"
  FOR EACH ROW EXECUTE FUNCTION finance_append_only();

-- --- 7. Backfill ------------------------------------------------------------
-- One FinanceConfig singleton seeded with config/052-finance.yaml defaults.
-- updatedById points at an existing admin when available; otherwise the
-- first active user; the row is replaceable by the Admin write path
-- (config.updated audit) as soon as one runs.

DO $$ BEGIN
  INSERT INTO "FinanceConfig" (
    "id", "paymentMethods", "paymentSources", "expenseCategories",
    "approvalThreshold", "shopTimezone", "updatedById", "updatedAt"
  )
  SELECT
    'finance-config',
    '["Cash","Card","Bank transfer","InstaPay","Vodafone Cash","Cheque"]'::jsonb,
    '["Reception desk","Bank","Delivery driver"]'::jsonb,
    '[{"label":"Material","active":true},{"label":"External production","active":true},{"label":"Transport","active":true},{"label":"Maintenance","active":true},{"label":"Supplies","active":true},{"label":"Other","active":true}]'::jsonb,
    1000,
    'Africa/Cairo',
    (SELECT "id" FROM "user" WHERE "isActive" = true ORDER BY "createdAt" ASC LIMIT 1),
    CURRENT_TIMESTAMP
  WHERE EXISTS (SELECT 1 FROM "user")
    AND NOT EXISTS (SELECT 1 FROM "FinanceConfig" WHERE "id" = 'finance-config');
EXCEPTION WHEN unique_violation THEN NULL; WHEN not_null_violation THEN NULL; END $$;
